// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunch.Fiddler
{
    static class Vsix
    {
        public const string Id = "8848b323-a859-40fa-88ff-ae80d5ad6198";
        public const string Name = "QuickLaunchFiddler";
        public const string Description = @"Open multiple files simultaneously in Altova XMLSpy XML Editor directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Greg Trevellick";
        public const string Tags = "xml, xmlspy, altova, xsd, xslt, open, open in";
    }
}
