// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunchFiddler
{
    static class Vsix
    {
        public const string Id = "QuickLaunchFiddler.8848b323-a859-40fa-88ff-ae80d5ad6198";
        public const string Name = "QuickLaunchFiddler";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "";
    }
}
