// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunch.Fiddler
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidQuickButtonCommandPackageString = "fbde4ce1-b539-4eb7-af0b-8b876f24a84d";
        public const string guidQuickButtonCommandPackageCmdSetString = "7aaba3a9-97d0-41d2-b4c4-b543912979a0";
        public const string guidImagesString = "efe2a67d-72d5-43d8-8f14-e6748f3d967f";
        public static Guid guidQuickButtonCommandPackage = new Guid(guidQuickButtonCommandPackageString);
        public static Guid guidQuickButtonCommandPackageCmdSet = new Guid(guidQuickButtonCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IdmVsMenuTools = 0x1020;
        public const int QuickButtonCommandId456 = 0x0100;
        public const int ToolbarGroup123 = 0x1050;
        public const int QuickLaunchToolBar456 = 0x1000;
        public const int ToolsMenuQuickLaunchSubMenu = 0x1100;
        public const int SubMenuGroup789 = 0x1150;
        public const int bmpPic1 = 0x0001;
    }
}
