// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunch.Fiddler
{
    static class Vsix
    {
        public const string Id = "8848b323-a859-40fa-88ff-ae80d5ad6198";
        public const string Name = "Open Fiddler";
        public const string Description = @"Adds toolbar button and tools menu button to launch Fiddler";
        public const string Language = "en-US";
        public const string Version = "1.0.10";
        public const string Author = "Greg Trevellick";
        public const string Tags = "quicklaunch, quick launch, quick, launch, fiddler";
    }
}
