// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunch.Fiddler
{
    static class Vsix
    {
        public const string Id = "CustomCommandSample.b533325b-3cbb-40bc-a4e8-9f4221c0b01c";
        public const string Name = "Custom Command Sample";
        public const string Description = @"Shows how to hook up a command in VS";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "sample, command";
    }
}
