// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunch.Wireshark
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidQuickButtonCommandPackageString = "225412ef-c808-4790-8074-6be2bce92498";
        public const string guidQuickButtonCommandPackageCmdSetString = "945d2127-2ff5-480c-ab40-2cfdb794e373";
        public const string guidImagesString = "d79111cd-385c-4449-bfd0-3364fcb5a21b";
        public static Guid guidQuickButtonCommandPackage = new Guid(guidQuickButtonCommandPackageString);
        public static Guid guidQuickButtonCommandPackageCmdSet = new Guid(guidQuickButtonCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int QuickButtonCommandId = 0x0100;
        public const int QLToolbarGroup = 0x1050;
        public const int QuickLaunchToolBar = 0x1000;
        public const int ToolsMenuQuickLaunch = 0x1100;
        public const int bmpPic1 = 0x0001;
    }
}
