// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickLaunch.Wireshark
{
    static class Vsix
    {
        public const string Id = "BDA39C0E-35E7-413C-A4FF-511A79DA0848";
        public const string Name = "Open Wireshark";
        public const string Description = @"Adds toolbar button and tools menu button to launch Wireshark

";
        public const string Language = "en-US";
        public const string Version = "1.0.7";
        public const string Author = "Greg Trevellick";
        public const string Tags = "quicklaunch, quick launch, quick, launch, Wireshark";
    }
}
