// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject3
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidQuickButtonCommandPackageString = "462b1151-d39e-4099-b947-7702b6b60e9b";
        public const string guidQuickButtonCommandPackageCmdSetString = "ea775f15-152c-46d2-b8c1-7819c9fb5bff";
        public const string guidImagesString = "bc7d8ca2-3ee8-4937-adea-7bdb122b2124";
        public static Guid guidQuickButtonCommandPackage = new Guid(guidQuickButtonCommandPackageString);
        public static Guid guidQuickButtonCommandPackageCmdSet = new Guid(guidQuickButtonCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int QuickButtonCommandId = 0x0100;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
